local NpcData = {} 

   NpcData.NPCs = {
	["NPC1"] = {
		["Name"] = "NPC1",
		["Price"] = 0,
		["Rarity"] = "Common",
		["MoneyPerSec"] = 5
	},
	["NPC2"] = {
		["Name"] = "NPC2",
		["Price"] = 200,
		["Rarity"] = "Uncommon",
		["MoneyPerSec"] = 10
	},
	["NPC3"] = {
		["Name"] = "NPC3",
		["Price"] = 300,
		["Rarity"] = "Rare",
		["MoneyPerSec"] = 15
	},
	["NPC4"] = {
		["Name"] = "NPC4",
		["Price"] = 400,
		["Rarity"] = "Epic",
		["MoneyPerSec"] = 20
	},
	["NPC5"] = {
		["Name"] = "NPC5",
		["Price"] = 500,
		["Rarity"] = "Legendary",
		["MoneyPerSec"] = 25
	},
	
}
return NpcData
